"""Initial migration

Revision ID: 826fcbc57eb4
Revises: 
Create Date: 2025-08-09 13:40:27.211123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826fcbc57eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayah_index',
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_no', sa.Integer(), nullable=False),
    sa.Column('text_plain', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('surah_id', 'ayah_no')
    )
    op.create_table('reciters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reciters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reciters_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_or_phone', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email_or_phone'), ['email_or_phone'], unique=True)

    op.create_table('downloads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reciter_id', sa.Integer(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reciter_id'], ['reciters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reciter_id', 'surah_id'),
    sa.UniqueConstraint('user_id', 'reciter_id', 'surah_id', name='uq_downloads_user_reciter_surah')
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_user_id'), ['user_id'], unique=False)

    op.create_table('progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_no', sa.Integer(), nullable=False),
    sa.Column('ef', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'surah_id', 'ayah_no'),
    sa.UniqueConstraint('user_id', 'surah_id', 'ayah_no', name='uq_progress_user_surah_ayah')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('ayah_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'due_date', 'surah_id', 'ayah_no', name='uq_review_queue_user_date_surah_ayah')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reciter_id', sa.Integer(), nullable=True),
    sa.Column('default_speed', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('tajweed_enabled', sa.Boolean(), nullable=False),
    sa.Column('font_scale', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reciter_id'], ['reciters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('playlist_items',
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('from_surah', sa.Integer(), nullable=False),
    sa.Column('from_ayah', sa.Integer(), nullable=False),
    sa.Column('to_surah', sa.Integer(), nullable=False),
    sa.Column('to_ayah', sa.Integer(), nullable=False),
    sa.Column('repeat', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'position'),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_item_playlist_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_items')
    op.drop_table('user_settings')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_due_date'))

    op.drop_table('review_queue')
    op.drop_table('progress')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_user_id'))

    op.drop_table('playlists')
    op.drop_table('downloads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_or_phone'))

    op.drop_table('users')
    with op.batch_alter_table('reciters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reciters_code'))

    op.drop_table('reciters')
    op.drop_table('ayah_index')
    # ### end Alembic commands ###
